### ISSUE TITLE
Adapter still useable?

### ISSUE THREAD

**Issue by mcm1957** [DrozmotiX/ioBroker.coronavirus-statistics#357] opened 2023-06-05 11:50 UTC
Is this adapter still useable?

Sentry reports several issues:
https://sentry.iobroker.net/organizations/iobroker/issues/?project=30

Generic Source : https://coronavirus-19-api.herokuapp.com/ seems to be offline.

**Comment by mcm1957** [comment] 2023-06-16 06:48
![image](https://github.com/DrozmotiX/ioBroker.coronavirus-statistics/assets/28575778/45d1fd40-45f4-45cf-8f28-c56aa5a98cef)

**Comment by mcm1957** [comment] 2023-06-16 06:49
@DrozmotiX
Please let us know wether this adapter is still usable (and sentry errors will be corrected) or it should be archived as no more corona data ios published.

Thanks

**Comment by mcm1957** [comment] 2023-08-03 13:45
https://github.com/DrozmotiX
@DutchmanNL

Please let us know wether this adapter is still usable (and sentry errors will be corrected) or it should be archived as no more corona data ios published.

Thanks

**Comment by DutchmanNL** [comment] 2023-08-04 14:42
> https://github.com/DrozmotiX @DutchmanNL
> 
> Please let us know wether this adapter is still usable (and sentry errors will be corrected) or it should be archived as no more corona data ios published.
> 
> Thanks

will check this weekend, if the API is dead it will be a deprecated adapter and if it will be a a lot of effort to adopt new structures true we will also deprecate as luckily the information need is not that high anymore.

Will let you know after weekend, holiday period here :)

**Comment by mcm1957** [comment] 2023-09-04 12:30
@DutchmanNL 
Dis you have time for a check in the meantime?

**Comment by DutchmanNL** [comment] 2023-09-21 20:52
adapter works fine for generic data provided by official API of disease were this adapter was designed for so no action needed an all up-to-date.

Several specific local German API for "Bunderslaender" looks like been not available anymore so that specific data may be missing but no development on that possible as API's are closed.

I will close this issue as generic remark, no big issue mention on git which need effort.
For the German parts, I think will make an update to remove it as there is now high need or better said... no data available anymore on the API provided during covid pandemi

**Closed by DutchmanNL** 2023-09-21 20:52 UTC
